//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.09 at 03:49:51 PM PDT 
//


package com.vegaspbs.types.ed2go;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Course complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Course"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Title" type="{https://api.ed2go.com/}EncodedValue" minOccurs="0"/&gt;
 *         &lt;element name="Summary" type="{https://api.ed2go.com/}EncodedValue" minOccurs="0"/&gt;
 *         &lt;element name="Overview" type="{https://api.ed2go.com/}EncodedValue" minOccurs="0"/&gt;
 *         &lt;element name="Details" type="{https://api.ed2go.com/}EncodedValue" minOccurs="0"/&gt;
 *         &lt;element name="Outline" type="{https://api.ed2go.com/}EncodedValue" minOccurs="0"/&gt;
 *         &lt;element name="Objectives" type="{https://api.ed2go.com/}EncodedValue" minOccurs="0"/&gt;
 *         &lt;element name="FAQs" type="{https://api.ed2go.com/}EncodedValue" minOccurs="0"/&gt;
 *         &lt;element name="Requirements" type="{https://api.ed2go.com/}EncodedValue" minOccurs="0"/&gt;
 *         &lt;element name="Prerequisites" type="{https://api.ed2go.com/}EncodedValue" minOccurs="0"/&gt;
 *         &lt;element name="Instructor" type="{https://api.ed2go.com/}EncodedValue" minOccurs="0"/&gt;
 *         &lt;element name="Duration" type="{https://api.ed2go.com/}Duration" minOccurs="0"/&gt;
 *         &lt;element name="Hours" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="Image" type="{https://api.ed2go.com/}EncodedValue" minOccurs="0"/&gt;
 *         &lt;element name="Index" type="{https://api.ed2go.com/}EncodedValue" minOccurs="0"/&gt;
 *         &lt;element name="Demo" type="{https://api.ed2go.com/}EncodedValue" minOccurs="0"/&gt;
 *         &lt;element name="ReleaseDate" type="{https://api.ed2go.com/}Date" minOccurs="0"/&gt;
 *         &lt;element name="DiscontinueDate" type="{https://api.ed2go.com/}Date" minOccurs="0"/&gt;
 *         &lt;element name="LastModifiedDate" type="{https://api.ed2go.com/}Date" minOccurs="0"/&gt;
 *         &lt;element name="VendorCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="StartDates" type="{https://api.ed2go.com/}ArrayOfDate" minOccurs="0"/&gt;
 *         &lt;element name="RelatedCourses" type="{https://api.ed2go.com/}ArrayOfCourseCode" minOccurs="0"/&gt;
 *         &lt;element name="StudentReviews" type="{https://api.ed2go.com/}ArrayOfStudentReview" minOccurs="0"/&gt;
 *         &lt;element name="CategoryIDs" type="{https://api.ed2go.com/}ArrayOfCategoryID" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="CourseCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Course", propOrder = {
    "title",
    "summary",
    "overview",
    "details",
    "outline",
    "objectives",
    "faQs",
    "requirements",
    "prerequisites",
    "instructor",
    "duration",
    "hours",
    "image",
    "index",
    "demo",
    "releaseDate",
    "discontinueDate",
    "lastModifiedDate",
    "vendorCode",
    "startDates",
    "relatedCourses",
    "studentReviews",
    "categoryIDs"
})
public class Course {

    @XmlElement(name = "Title")
    protected EncodedValue title;
    @XmlElement(name = "Summary")
    protected EncodedValue summary;
    @XmlElement(name = "Overview")
    protected EncodedValue overview;
    @XmlElement(name = "Details")
    protected EncodedValue details;
    @XmlElement(name = "Outline")
    protected EncodedValue outline;
    @XmlElement(name = "Objectives")
    protected EncodedValue objectives;
    @XmlElement(name = "FAQs")
    protected EncodedValue faQs;
    @XmlElement(name = "Requirements")
    protected EncodedValue requirements;
    @XmlElement(name = "Prerequisites")
    protected EncodedValue prerequisites;
    @XmlElement(name = "Instructor")
    protected EncodedValue instructor;
    @XmlElement(name = "Duration")
    protected Duration duration;
    @XmlElementRef(name = "Hours", namespace = "https://api.ed2go.com/", type = JAXBElement.class, required = false)
    protected JAXBElement<BigDecimal> hours;
    @XmlElement(name = "Image")
    protected EncodedValue image;
    @XmlElement(name = "Index")
    protected EncodedValue index;
    @XmlElement(name = "Demo")
    protected EncodedValue demo;
    @XmlElement(name = "ReleaseDate")
    protected Date releaseDate;
    @XmlElement(name = "DiscontinueDate")
    protected Date discontinueDate;
    @XmlElement(name = "LastModifiedDate")
    protected Date lastModifiedDate;
    @XmlElement(name = "VendorCode")
    protected String vendorCode;
    @XmlElement(name = "StartDates")
    protected ArrayOfDate startDates;
    @XmlElement(name = "RelatedCourses")
    protected ArrayOfCourseCode relatedCourses;
    @XmlElement(name = "StudentReviews")
    protected ArrayOfStudentReview studentReviews;
    @XmlElement(name = "CategoryIDs")
    protected ArrayOfCategoryID categoryIDs;
    @XmlAttribute(name = "CourseCode")
    protected String courseCode;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link EncodedValue }
     *     
     */
    public EncodedValue getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncodedValue }
     *     
     */
    public void setTitle(EncodedValue value) {
        this.title = value;
    }

    /**
     * Gets the value of the summary property.
     * 
     * @return
     *     possible object is
     *     {@link EncodedValue }
     *     
     */
    public EncodedValue getSummary() {
        return summary;
    }

    /**
     * Sets the value of the summary property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncodedValue }
     *     
     */
    public void setSummary(EncodedValue value) {
        this.summary = value;
    }

    /**
     * Gets the value of the overview property.
     * 
     * @return
     *     possible object is
     *     {@link EncodedValue }
     *     
     */
    public EncodedValue getOverview() {
        return overview;
    }

    /**
     * Sets the value of the overview property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncodedValue }
     *     
     */
    public void setOverview(EncodedValue value) {
        this.overview = value;
    }

    /**
     * Gets the value of the details property.
     * 
     * @return
     *     possible object is
     *     {@link EncodedValue }
     *     
     */
    public EncodedValue getDetails() {
        return details;
    }

    /**
     * Sets the value of the details property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncodedValue }
     *     
     */
    public void setDetails(EncodedValue value) {
        this.details = value;
    }

    /**
     * Gets the value of the outline property.
     * 
     * @return
     *     possible object is
     *     {@link EncodedValue }
     *     
     */
    public EncodedValue getOutline() {
        return outline;
    }

    /**
     * Sets the value of the outline property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncodedValue }
     *     
     */
    public void setOutline(EncodedValue value) {
        this.outline = value;
    }

    /**
     * Gets the value of the objectives property.
     * 
     * @return
     *     possible object is
     *     {@link EncodedValue }
     *     
     */
    public EncodedValue getObjectives() {
        return objectives;
    }

    /**
     * Sets the value of the objectives property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncodedValue }
     *     
     */
    public void setObjectives(EncodedValue value) {
        this.objectives = value;
    }

    /**
     * Gets the value of the faQs property.
     * 
     * @return
     *     possible object is
     *     {@link EncodedValue }
     *     
     */
    public EncodedValue getFAQs() {
        return faQs;
    }

    /**
     * Sets the value of the faQs property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncodedValue }
     *     
     */
    public void setFAQs(EncodedValue value) {
        this.faQs = value;
    }

    /**
     * Gets the value of the requirements property.
     * 
     * @return
     *     possible object is
     *     {@link EncodedValue }
     *     
     */
    public EncodedValue getRequirements() {
        return requirements;
    }

    /**
     * Sets the value of the requirements property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncodedValue }
     *     
     */
    public void setRequirements(EncodedValue value) {
        this.requirements = value;
    }

    /**
     * Gets the value of the prerequisites property.
     * 
     * @return
     *     possible object is
     *     {@link EncodedValue }
     *     
     */
    public EncodedValue getPrerequisites() {
        return prerequisites;
    }

    /**
     * Sets the value of the prerequisites property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncodedValue }
     *     
     */
    public void setPrerequisites(EncodedValue value) {
        this.prerequisites = value;
    }

    /**
     * Gets the value of the instructor property.
     * 
     * @return
     *     possible object is
     *     {@link EncodedValue }
     *     
     */
    public EncodedValue getInstructor() {
        return instructor;
    }

    /**
     * Sets the value of the instructor property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncodedValue }
     *     
     */
    public void setInstructor(EncodedValue value) {
        this.instructor = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setDuration(Duration value) {
        this.duration = value;
    }

    /**
     * Gets the value of the hours property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getHours() {
        return hours;
    }

    /**
     * Sets the value of the hours property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setHours(JAXBElement<BigDecimal> value) {
        this.hours = value;
    }

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     {@link EncodedValue }
     *     
     */
    public EncodedValue getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncodedValue }
     *     
     */
    public void setImage(EncodedValue value) {
        this.image = value;
    }

    /**
     * Gets the value of the index property.
     * 
     * @return
     *     possible object is
     *     {@link EncodedValue }
     *     
     */
    public EncodedValue getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncodedValue }
     *     
     */
    public void setIndex(EncodedValue value) {
        this.index = value;
    }

    /**
     * Gets the value of the demo property.
     * 
     * @return
     *     possible object is
     *     {@link EncodedValue }
     *     
     */
    public EncodedValue getDemo() {
        return demo;
    }

    /**
     * Sets the value of the demo property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncodedValue }
     *     
     */
    public void setDemo(EncodedValue value) {
        this.demo = value;
    }

    /**
     * Gets the value of the releaseDate property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getReleaseDate() {
        return releaseDate;
    }

    /**
     * Sets the value of the releaseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setReleaseDate(Date value) {
        this.releaseDate = value;
    }

    /**
     * Gets the value of the discontinueDate property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getDiscontinueDate() {
        return discontinueDate;
    }

    /**
     * Sets the value of the discontinueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setDiscontinueDate(Date value) {
        this.discontinueDate = value;
    }

    /**
     * Gets the value of the lastModifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * Sets the value of the lastModifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setLastModifiedDate(Date value) {
        this.lastModifiedDate = value;
    }

    /**
     * Gets the value of the vendorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorCode() {
        return vendorCode;
    }

    /**
     * Sets the value of the vendorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorCode(String value) {
        this.vendorCode = value;
    }

    /**
     * Gets the value of the startDates property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfDate }
     *     
     */
    public ArrayOfDate getStartDates() {
        return startDates;
    }

    /**
     * Sets the value of the startDates property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfDate }
     *     
     */
    public void setStartDates(ArrayOfDate value) {
        this.startDates = value;
    }

    /**
     * Gets the value of the relatedCourses property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfCourseCode }
     *     
     */
    public ArrayOfCourseCode getRelatedCourses() {
        return relatedCourses;
    }

    /**
     * Sets the value of the relatedCourses property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfCourseCode }
     *     
     */
    public void setRelatedCourses(ArrayOfCourseCode value) {
        this.relatedCourses = value;
    }

    /**
     * Gets the value of the studentReviews property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfStudentReview }
     *     
     */
    public ArrayOfStudentReview getStudentReviews() {
        return studentReviews;
    }

    /**
     * Sets the value of the studentReviews property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfStudentReview }
     *     
     */
    public void setStudentReviews(ArrayOfStudentReview value) {
        this.studentReviews = value;
    }

    /**
     * Gets the value of the categoryIDs property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfCategoryID }
     *     
     */
    public ArrayOfCategoryID getCategoryIDs() {
        return categoryIDs;
    }

    /**
     * Sets the value of the categoryIDs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfCategoryID }
     *     
     */
    public void setCategoryIDs(ArrayOfCategoryID value) {
        this.categoryIDs = value;
    }

    /**
     * Gets the value of the courseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseCode() {
        return courseCode;
    }

    /**
     * Sets the value of the courseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseCode(String value) {
        this.courseCode = value;
    }

}
