//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.09 at 03:49:51 PM PDT 
//


package com.vegaspbs.api_ed2go;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ErrorCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ErrorCode"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="None"/&gt;
 *     &lt;enumeration value="InvalidParameter"/&gt;
 *     &lt;enumeration value="MissingParameter"/&gt;
 *     &lt;enumeration value="DuplicateParameter"/&gt;
 *     &lt;enumeration value="UnknownServerError"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ErrorCode")
@XmlEnum
public enum ErrorCode {

    @XmlEnumValue("None")
    NONE("None"),
    @XmlEnumValue("InvalidParameter")
    INVALID_PARAMETER("InvalidParameter"),
    @XmlEnumValue("MissingParameter")
    MISSING_PARAMETER("MissingParameter"),
    @XmlEnumValue("DuplicateParameter")
    DUPLICATE_PARAMETER("DuplicateParameter"),
    @XmlEnumValue("UnknownServerError")
    UNKNOWN_SERVER_ERROR("UnknownServerError");
    private final String value;

    ErrorCode(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ErrorCode fromValue(String v) {
        for (ErrorCode c: ErrorCode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
