//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.09 at 03:49:51 PM PDT 
//


package com.vegaspbs.api_ed2go;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CoursesGetResponse" type="{https://api.ed2go.com/}CoursesResponse" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "coursesGetResponse"
})
@XmlRootElement(name = "GetCoursesResponse")
public class GetCoursesResponse {

    @XmlElement(name = "CoursesGetResponse")
    protected CoursesResponse coursesGetResponse;

    /**
     * Gets the value of the coursesGetResponse property.
     * 
     * @return
     *     possible object is
     *     {@link CoursesResponse }
     *     
     */
    public CoursesResponse getCoursesGetResponse() {
        return coursesGetResponse;
    }

    /**
     * Sets the value of the coursesGetResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoursesResponse }
     *     
     */
    public void setCoursesGetResponse(CoursesResponse value) {
        this.coursesGetResponse = value;
    }

}
